[project]
name = "yolo12n-face-identification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chardet>=5.2.0",
    "python-dotenv>=1.0.0",
    "numpy>=2.4.0",
    "swanlab>=0.7.5",
    "ultralytics>=8.3.241",
]
